version: "3.9"

services:
  django:
    image: streamer:latest
    command: gunicorn -b 0.0.0.0 -p 8000 config.wsgi:application
    volumes:
      - "./:/Streamer"
    depends_on:
      - postgres
      - redis
      - celery
    network_mode: host

  celery:
    image: streamer:latest
    command: celery -A config worker -l INFO
    volumes:
      - "./:Streamer"
    depends_on:
     - postgres
     - redis
    network_mode: host

  redis:
    image: redis:latest
    network_mode: host
    volumes:
      - redis_data:/data
  
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=value
      - POSTGRES_HOST=value
      - POSTGRES_NAME=value
      - POSTGRES_PASSWORD=value
    network_mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - "./:Streamer"
    depends_on:
      - postgres
      - redis
      - celery
      - django
    network_mode: host

volumes:
  postgres_data:
  redis_data:
