# Generated by Django 4.2.7 on 2023-12-07 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import streamer.stream.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stream",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                (
                    "music",
                    models.FileField(
                        upload_to=streamer.stream.models.Stream.upload_music_file
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=512, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=streamer.stream.models.Stream.upload_thumb_file,
                    ),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="streamed_musics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
