global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: django
    metrics_path: /metrics
    static_configs:
      - targets: ['django-svc:8000']