apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/websocket-services: "channels-svc"
spec:
  rules:
  - host: devoreal.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: django-svc
            port:
              number: 8000
  - host: devoreal.top
    http:
      paths:
      - path: /ws/
        pathType: Prefix
        backend:
          service:
            name: channels-svc
            port:
              number: 8001
  - host: grafana.devoreal.top
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana-svc
            port:
              number: 3000
