apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  labels:
    name: nginx-ingress
spec:
  rules:
  - host: devo.devoreal.top
    http:
      paths:
      - pathType: django
        path: "/"
        backend:
          service:
            name: django-svc
            port: 
              number: 80
      - pathType: channels
        path: "/ws"
        backend:
          service:
            name: channels-svc
            port:
              number: 80
