apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: django-svc
            port:
              number: 8000
  - http:
      paths:
      - path: /ws/
        pathType: Prefix
        backend:
          service:
            name: channels-svc
            port:
              number: 8001
  - http:
      paths:
      - path: /prometheus/
        pathType: Prefix
        backend:
          service:
            name: prometheus-svc
            port:
              number: 9090
  - http:
      paths:
      - path: /monitor/
        pathType: Prefix
        backend:
          service:
            name: grafana-svc
            port:
              number: 3000
