version: "3.9"

services:
  django:
    image: streamer:latest
    command: gunicorn -b 0.0.0.0 -p 8000 config.wsgi:application
    env_file: .streamer
    volumes:
      - "./:/Streamer"
    depends_on:
      - postgres
      - redis
      - celery
    network_mode: host

  channels:
    image: streamer:latest
    command: uvicorn --bind 0.0.0.0 -p 8001 config.wsgi:application
    env_file: .streamer
    volumes:
      - "./:/Streamer"
    depends_on:
      - postgres
      - redis
      - celery
    network_mode: host

  celery:
    image: streamer:latest
    command: celery -A config worker -l INFO
    env_file: .streamer
    volumes:
      - "./:Streamer"
    depends_on:
     - postgres
     - redis
    network_mode: host

  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    env_file: env/.redis
    network_mode: host
    volumes:
      - redis_data:/data
  
  postgres:
    image: postgres:latest
    env_file: env/.postgres
    network_mode: host
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    volumes:
      - "./:Streamer"
      - "./nginx/streamer.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - postgres
      - redis
      - celery
      - django
    network_mode: host

volumes:
  postgres_data:
  redis_data: