apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deploy
spec:
  selector:
    matchLabels:
      app: celery-deploy
  template:
    metadata:
      labels:
        app: celery-deploy
    spec:
      imagePullSecrets:
      - name: dockerauth
      containers:
      - name: celery-container
        image: devomini/streamer:latest
        command: 
          - "celery"
          - "-A"
          - "config"
          - "worker"
          - "-l"
          - "INFO"
        ports:
        - containerPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: celery-svc
spec:
  selector:
    app: celery-deploy
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
  type: NodePort