apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-deploy
  template:
    metadata:
      labels:
        app: celery-deploy
    spec:
      containers:
      - name: celery-deploy
        image: devomini/streamer:latest
        command: 
          - "celery"
          - "-A"
          - "config"
          - "worker"
          - "-l"
          - "INFO"
        ports:
        - containerPort: 8002
        resources:
          limits:
            cpu: "200m"
            memory: "500"

---
apiVersion: v1
kind: Service
metadata:
  name: celery-svc
spec:
  type: NodePort
  ports:
  - port: 8002
    targetPort: 8002
    protocol: TCP
    name: http
  selector:
    app: celery-deploy
