apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-deploy
spec:
  selector:
    matchLabels:
      app: celery-pod
  template:
    metadata:
      labels:
        app: celery-pod
    spec:
      imagePullSecrets:
      - name: dockerauth
      containers:
      - name: celery-container
        image: devomini/streamer:latest
        command: 
          - "celery"
          - "-A"
          - "config"
          - "worker"
          - "-l"
          - "INFO"
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 8002

---
apiVersion: v1
kind: Service
metadata:
  name: celery-svc
spec:
  selector:
    app: celery-deploy
  ports:
  - port: 8002
    targetPort: 8002
