apiVersion: apps/v1
kind: Deployment
metadata:
  name: channels-deploy
spec:
  selector:
    matchLabels:
      app: channels-deploy
  template:
    metadata:
      labels:
        app: channels-deploy
    spec:
      containers:
      - name: channels-deploy
        image: streamer:latest
        command: ["uvicorn -b 0.0.0.0 -p 8000 config.wsgi.application"]
        resources:
          limits:
            memory: "128Mi"
            cpu: "200m"
        ports:
        - containerPort: 8001
    imagePullSecrets:
      - name: dockerauth

---
apiVersion: v1
kind: Service
metadata:
  name: channels-svc
spec:
  selector:
    app: channels-deploy
  ports:
  - port: 8001
    targetPort: 8001
