apiVersion: apps/v1
kind: Deployment
metadata:
  name: channels-deploy
spec:
  selector:
    matchLabels:
      app: channels-pod
  template:
    metadata:
      labels:
        app: channels-pod
    spec:
      imagePullSecrets:
      - name: dockerauth
      containers:
      - name: channels-container
        image: devomini/streamer:latest
        command: 
          - "uvicorn"
          - "--host"
          - "0.0.0.0"
          - "--port" 
          - "8001"
          - "config.asgi:application"
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - containerPort: 8001

---
apiVersion: v1
kind: Service
metadata:
  name: channels-svc
spec:
  selector:
    app: channels-deploy
  ports:
  - port: 8001
    targetPort: 8001
