apiVersion: apps/v1
kind: Deployment
metadata:
  name: channels-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: channels-deploy
  template:
    metadata:
      labels:
        app: channels-deploy
    spec:
      containers:
      - name: channels-deploy
        image: devomini/streamer:latest
        command: 
          - "uvicorn"
          - "--host"
          - "0.0.0.0"
          - "--port" 
          - "8001"
          - "config.asgi:application"
        ports:
        - containerPort: 8001
        resources:
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: channels-svc
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
    name: http
  selector:
    app: channels-deploy
