apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: django-deploy
  template:
    metadata:
      labels:
        app: django-deploy
    spec:
      containers:
      - name: django-deploy
        image: devomini/streamer:latest
        command:
        - "gunicorn"
        - "-b"
        - "0.0.0.0"
        - "-p"
        - "8000"
        - "config.wsgi:application"
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: django-svc
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: django-deploy
