- hosts: 139.162.139.72
  become: true
  vars:
    services_to_start:
      - jenkins
      - docker
    packages_to_install:
      - python3-pip
      - python3-virtualenv
      - docker-compose

  tasks:
    - name: Update and upgrade system packages
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: true

    - name: Installing required packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages_to_install }}"

    - name: Add Docker GPG apt key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      ansible.builtin.apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update Repository and install docker-ce
      ansible.builtin.apt:
        name: docker-ce
        state: present
        update_cache: true

    # - name: Log into DockerHub
    #   docker_login:
    #     username: devomini
    #     password: Abc123@#$

    - name: add Kubernetes apt-key for APT repository
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: add Kubernetes APT repository
      apt_repository:
       repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
       state: present
       filename: 'kubernetes'

    - name: install k8s tools
      apt:
        name:
          - kubelet
          - kubernetes-cni
          - kubeadm
          - kubectl
        state: present
        update_cache: true

    - name: Install Minikube
      ansible.builtin.shell:
        curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && sudo install minikube-linux-amd64 /usr/local/bin/minikube
  
    - name: Installing jdk-11
      ansible.builtin.apt:
        name: openjdk-11-jdk
        state: present

    - name: Add jenkins GPG apt key
      ansible.builtin.apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

    - name: Add jenkins to Repository
      ansible.builtin.apt_repository:
        repo: deb https://pkg.jenkins.io/debian-stable binary/
        state: present

    - name: Install jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    - name: Add Jenkins to root group
      ansible.builtin.shell: usermod -a -G root jenkins

    - name: Start jenkins and docker services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
      with_items: "{{ services_to_start }}"

    - name: Running Minikube start
      ansible.builtin.shell: minikube start --driver=docker --force
      become: false

    - name: Getting password of jenkins
      ansible.builtin.command: cat /var/lib/jenkins/secrets/initialAdminPassword
      register: password

    - name: Show output
      ansible.builtin.debug:
        var: password.stdout_lines
